Fixed order of operations in cwa-init that resulted in new app.db files having root permissions and not being writable for new users (Issue #242)

diff --git a/root/etc/s6-overlay/s6-rc.d/cwa-init/run b/root/etc/s6-overlay/s6-rc.d/cwa-init/run
--- a/root/etc/s6-overlay/s6-rc.d/cwa-init/run
+++ b/root/etc/s6-overlay/s6-rc.d/cwa-init/run
@@ -12,29 +12,6 @@ mkdir -p /config/log_archive
 mkdir -p /config/.cwa_conversion_tmp
 
 #------------------------------------------------------------------------------------------------------------------------
-#  Set required permissions
-#------------------------------------------------------------------------------------------------------------------------
-
-declare -a requiredDirs=("/config" "/calibre-library" "/app/calibre-web-automated")
-
-dirs=$(printf ", %s" "${requiredDirs[@]}")
-dirs=${dirs:1}
-
-echo "[cwa-init] Recursively setting ownership of everything in$dirs to abc:abc..."
-
-for d in "${requiredDirs[@]}"
-do
-    chown -R abc:abc $d
-    if [[ $? == 0 ]]
-    then
-        echo "[cwa-init] Successfully set permissions for '$d'!"
-    elif [[ $? > 0 ]]
-    then
-        echo "[cwa-init] Service could not successfully set permissions for '$d' (see errors above)."
-    fi
-done
-
-#------------------------------------------------------------------------------------------------------------------------
 #  Remove any leftover lock files
 #------------------------------------------------------------------------------------------------------------------------
 
@@ -95,3 +72,26 @@ fi
 
 
 echo "[cwa-init] CWA-init complete! Service exiting now..."
+
+#------------------------------------------------------------------------------------------------------------------------
+#  Set required permissions
+#------------------------------------------------------------------------------------------------------------------------
+
+declare -a requiredDirs=("/config" "/calibre-library" "/app/calibre-web-automated")
+
+dirs=$(printf ", %s" "${requiredDirs[@]}")
+dirs=${dirs:1}
+
+echo "[cwa-init] Recursively setting ownership of everything in$dirs to abc:abc..."
+
+for d in "${requiredDirs[@]}"
+do
+    chown -R abc:abc $d
+    if [[ $? == 0 ]]
+    then
+        echo "[cwa-init] Successfully set permissions for '$d'!"
+    elif [[ $? > 0 ]]
+    then
+        echo "[cwa-init] Service could not successfully set permissions for '$d' (see errors above)."
+    fi
+done
